p_load_sfdc_opportunity_churn_data

Alter step s_load_sfdc_opportunity_churn_data_prestage AS (
INSERT into Delta(TableName='delta.pstg_order_item_churn_prestage', Overwrite=true, Unlogged=true)
    SELECT opp.* FROM (
    SELECT Opportunity.Id AS Order_Code,
    Opportunity.Monthly_Validation__c as Monthly_Validation,
    Nvl(Opportunity.PrimaryProduct__r.Name || '_Churn_' || Opportunity.Churn_Date__c, 'No Product_' || 'Churn_' || Opportunity.Churn_Date__c) AS item_code,
    'Opportunity Churn' AS Batch_Type,
    CASE
    WHEN (Month(ToDate(Opportunity.Churn_Date__c)) = '10' or Month(ToDate(Opportunity.Churn_Date__c)) = '11' or Month(ToDate(Opportunity.Churn_Date__c)) = '12')
    THEN Year(ToDate(Opportunity.Churn_Date__c)) || '_' || Month(ToDate(Opportunity.Churn_Date__c)) || '_Churn'
    ELSE Year(ToDate(Opportunity.Churn_Date__c)) || '_0' || Month(ToDate(Opportunity.Churn_Date__c)) || '_Churn'
    END AS Batch_Name,
    :v_param_processing_period as period_name,
    Opportunity.PrimaryProduct__r.Name AS Product_name,
    Opportunity.End_User_Country__c AS Geography_name,
    Account.Name AS Customer_Name,
    '1' AS Quantity,
    Nvl(Opportunity.Amount,0) AS Amount,
    'USD' AS amount_UnitType,
    ToDate(Opportunity.Churn_Date__c) AS incentive_date,
    ToDate(Approval_Process__r.CreatedDate) AS Order_Date,
    'Opportunity Churn' AS order_type,
    NULL AS Discount,
    NULL AS Discount_UnitType,
    Opportunity.Name AS Description,
    Owner.employeeid__c AS Employee_id,
    '100' AS split_pct,
    ToDate(Opportunity.CloseDate) AS CloseDate,
    ToDate(Opportunity.Churn_Date__c) AS Churn_Date,
    Opportunity.ARR_Difference__c AS Final_ARR_Growth,
    CASE when (Opportunity.ARR_Difference__c IS NOT NULL) THEN 'USD' ELSE NULL END AS Final_ARR_Growth_UnitType,
    Opportunity.StageName AS StageName,
    Opportunity.Related_Contracts_ARR_Formula__c AS Related_Contract_ARR,
    CASE when (Opportunity.Related_Contracts_ARR_Formula__c IS NOT NULL) THEN 'USD' ELSE NULL END AS Related_Contract_ARR_UnitType,
    Opportunity.Current_ARR__c AS Final_Contract_ARR,
    CASE when (Opportunity.Current_ARR__c IS NOT NULL) THEN 'USD' ELSE NULL END AS Final_Contract_ARR_UnitType,
    Reseller_Account__r.Name AS Reseller_Account,
    Opportunity.Approval_Done__c AS Approval_Done,
    Opportunity.Renewal_Credit_Amount_ARR__c AS Renewal_ARR,
    CASE when (Opportunity.Renewal_Credit_Amount_ARR__c IS NOT NULL) THEN 'USD' ELSE NULL END AS Renewal_ARR_UnitType,
    ToDate(Approval_Process__r.CreatedDate) AS Deal_Date,
    Opportunity.Renewal_Type__c AS Renewal_Type,
    Opportunity.Record_Type_Name__c AS Record_Type_Name,
    Opportunity.Out_of_Recovery_Period__c AS Out_of_Recovery_Period,
    Opportunity.LeadSource AS Lead_Source,
    Approval_Process__r.Description__c AS Opportunity_Description,
    Opportunity.Previous_ARR__c AS Previous_ARR,
    CASE when (Opportunity.Previous_ARR__c IS NOT NULL) THEN 'USD' ELSE NULL END AS Previous_ARR_UnitType,
    Opportunity.Consulting_Amount_Summary__c AS Consulting,
    CASE when (Opportunity.Consulting_Amount_Summary__c IS NOT NULL) THEN 'USD' ELSE NULL END AS Consulting_UnitType,
    Opportunity.Product_Platform__c AS Product_Type,
    Approval_Process__r.Approval_Sales_Manager__c AS Approval_Manager,
    Opportunity.Number_of_months_for_ARR__c AS ARR_Number_of_months,
    CASE when (Opportunity.Number_of_months_for_ARR__c IS NOT NULL) THEN 'USD' ELSE NULL END AS ARR_Number_of_months_UnitType,
    NULL AS Order_Process_Date,
    Opportunity.End_User_Country__c AS End_User_Country,
    Opportunity.Shipped_to_country__c AS Shipped_to_country,
    ToDate(Approval_Process__r.CreatedDate) As Approval_Process_Created_Date,
    Owner.userRole.name AS Approval_Process_Role,
    Approval_Process__r.Description__c AS System_Approval_Description,
    Opportunity_Contract_Unused_ARR_Amount__c AS Co_Termed_Unused_ARR,
    CASE when (Opportunity_Contract_Unused_ARR_Amount__c IS NOT NULL) THEN 'USD' ELSE NULL END AS Co_Termed_Unused_ARR_UnitType,
    Opportunity.Solution_Engineer__c as Opp_Solution_Engineer,
    Opportunity.Cloud_Migration__c as Opp_Cloud_Migration,
    Opportunity.Final_Number_of_Month__c as Opp_Final_Number_of_Month,
    Opportunity.Opp_Platform__c as Opp_Opp_Platform,
    CASE when (Opportunity.Strategic_Opportunity_Solution_Architect__c IS NOT NULL) THEN user.Name ELSE NULL END AS Opp_Strategic_Opp_Solution_Architect_name, 
    Opportunity.Strategic_Opportunity_Solution_Architect__c as Opp_Strategic_Opp_Solution_Architect,
    account.Business_Unit__r.Territory__c as Business_Unit_Territory,
    account.Business_Unit__r.Pod__c as Business_Unit_Pod,
    account.Business_Unit__r.Tier_Level__c as Business_Unit_Tier_Level,
    account.Business_Unit__r.Tier_Manager__r.Name as Business_Unit_Tier_Manager_Name,
    account.Business_Unit__r.Tier_Manager__c as Business_Unit_Tier_Manager_ID,
    account.Business_Unit__r.Regional_VP__r.Name as Business_Unit_Regional_VP_Name,
    account.Business_Unit__r.Pod_Manager__r.Name Business_Unit_Pod_Manager_Name,
    CSM__c Opp_CSM,
    Opportunity.Type Opp_Type,
    Opportunity.Owner.Name Opp_Owner_Name,
    Opportunity.Comp_Credit__c Opp_Comp_Credit,
    Opportunity.PS_Net_Amount__c as PS_Net_Amount,
    Opportunity.JAS_Net_Amount__c as JAS_Net_Amount,
    Opportunity.Co_Sell_Program_Opportunity__c as Co_Sell_Program_Opportunity,
    Opportunity.Marketplace_Offer_ID__c as Marketplace_Offer_ID,
    Opportunity.Partner_Lead_Source__c as Partner_Lead_Source,
    Opportunity.PRM_Opportunity_Origination__c as PRM_Opportunity_Origination,
    Opportunity.Cloud_Alliance_Partner__c as Cloud_Alliance_Partner
    , NULL as Qualified_Prospect
    , Nvl(arrb.Final_arr_growth__c,0) AS Security_Final_ARR_Growth,
    'USD' AS Security_Final_ARR_Growth_UnitTypeName,
    Opportunity.Security_Net_Amount__c AS Security_Net_Amount,
    IF Opportunity.Security_Net_Amount__c IS NOT NULL THEN 'USD'ELSE NULL END AS Security_Net_Amount_UnitTypeName,
    Opportunity.Cloud_Alliance_Co_Sell_Opportunity__c AS Cloud_Alliance_Co_Sell_Opportunity__c,
    Opportunity.Cloud_Alliance_Opportunity_ID__c AS Cloud_Alliance_Opportunity_ID__c, 
    NULL AS Meeting_Status,
    NULL AS Final_Qualified_Product,
    Opportunity.Purchese_Type__c AS Purchase_Type,
    IF Contains(Uppercase(Opportunity.PrimaryProduct__r.Name),'MONTHLY')=true THEN true ELSE false END AS Is_Monthly_Subscription_Product
    FROM SFDC(SOQL='select Id,
    Opportunity.Monthly_Validation__c,
    Opportunity.PrimaryProduct__r.Name,
    Opportunity_Contract_Unused_ARR_Amount__c,
    Opportunity.End_User_Country__c,
    Account.Name,
    Opportunity.Amount,
    Opportunity.Name,
    Opportunity.CloseDate,
    Opportunity.Churn_Date__c,
    Opportunity.ARR_Difference__c,
    Opportunity.StageName,
    Opportunity.Related_Contracts_ARR_Formula__c,
    Opportunity.Current_ARR__c,
    Opportunity.Reseller_Account__c,
    Reseller_Account__r.Name,
    Opportunity.Approval_Done__c,
    Opportunity.Renewal_Credit_Amount_ARR__c,
    Opportunity.Renewal_Type__c,
    Opportunity.Record_Type_Name__c,
    Opportunity.Out_of_Recovery_Period__c,
    Opportunity.LeadSource,
    Opportunity.Description,
    Opportunity.Previous_ARR__c,
    Opportunity.Consulting_Amount_Summary__c,
    Opportunity.Product_Platform__c,
    Opportunity.Number_of_months_for_ARR__c,
    Opportunity.Shipped_to_country__c,
    Owner.employeeid__c,
    CreatedDate,Opportunity.Solution_Engineer__c,
    Opportunity.Cloud_Migration__c,
    Opportunity.Final_Number_of_Month__c,
    Opportunity.Opp_Platform__c,
    Opportunity.Strategic_Opportunity_Solution_Architect__c,
    account.Business_Unit__r.Territory__c,
    account.Business_Unit__r.Pod__c,
    account.Business_Unit__r.Tier_Level__c,
    account.Business_Unit__r.Tier_Manager__r.Name,
    account.Business_Unit__r.Tier_Manager__c,
    account.Business_Unit__r.Regional_VP__r.Name,
    account.Business_Unit__r.Pod_Manager__r.Name, CSM__c,
    Opportunity.Type,Opportunity.Owner.Name,
    Opportunity.Comp_Credit__c,
    Opportunity.PS_Net_Amount__c,
    Opportunity.JAS_Net_Amount__c,
    Opportunity.Co_Sell_Program_Opportunity__c,
    Opportunity.Marketplace_Offer_ID__c,
    Opportunity.Partner_Lead_Source__c,
    Opportunity.PRM_Opportunity_Origination__c,
    Opportunity.Cloud_Alliance_Partner__c,
    Opportunity.Qualified_Prospect__c,
    Opportunity.Security_Net_Amount__c,
    Opportunity.Cloud_Alliance_Co_Sell_Opportunity__c,
    Opportunity.Cloud_Alliance_Opportunity_ID__c,
    Opportunity.Purchese_Type__c,
    (SELECT Id,Approval_Sales_Manager__c,OwnerId,Owner.userRole.name,CreatedDate,Description__c FROM Approval_Process__r where Description__c <> ''SDR Approval Process'' order by CreatedDate asc )
    FROM Opportunity where Opportunity.Churn_Date__c >= '||:v_var_sales_data_pp_start_date ||'AND Opportunity.Churn_Date__c <= '||:v_var_sales_data_pp_end_date ||' AND (Opportunity.StageName not in(''06-Closed Won'',''06-Closed Lost'') OR Opportunity.CloseDate >= ' || :v_var_sales_data_pp_end_date || ')',
    UserName=:v_sfdc_user,
    Password=:v_sfdc_passwd,
    Environment=:v_sfdc_env,
    ReadAll=false,
    Retries=2,
    RetryInterval=1
    )opp
    LEFT JOIN delta.generic_user_load user on LeftSide(opp.Strategic_Opportunity_Solution_Architect__c,15) = user.Id
    LEFT JOIN (SELECT Opp_id__c, Product_family__c, SUM(Final_arr_growth__c) AS Final_arr_growth__c
    FROM SFDC( SOQL='SELECT Opp_id__c, Final_arr_growth__c,Product_family__c FROM Arr_breakdown__x WHERE Product_family__c=''Security''',
    UserName=:v_sfdc_user,Password=:v_sfdc_passwd,Environment=:v_sfdc_env,ReadAll=false,Retries=2,RetryInterval=1)) arrb ON opp.Id=arrb.Opp_id__c
    ) opp
    WHERE opp.order_code NOT IN (SELECT order_code FROM delta.pstg_order_item_final)
    AND opp.order_code NOT in (select order_code, Incentive_Date from xactly.xc_comp_order_item WHERE Incentive_Date < :v_var_sales_data_pp_start_date and item_code like '%Churn%' GROUP BY Order_Code, Incentive_Date);
)

s_pstg_order_item_churn_order_count
INSERT into Delta(TableName='delta.pstg_order_item_churn_order_count', Overwrite=true, Unlogged=true)
    select order_code new_order_code, count(*) order_cnt from delta.pstg_order_item_churn_prestage

Alter step s_load_sfdc_opportunity_churn_data_final AS (
INSERT into Delta(TableName='delta.pstg_order_item_final', Overwrite=false, unlogged=false)
    SELECT
    Order_Code,
    item_code,
    Batch_Name,
    Batch_Type,
    period_name,
    Product_name,
    Geography_name,
    Customer_Name,
    Quantity,
    Amount,
    amount_UnitType,
    incentive_date,
    Order_Date,
    order_type,
    Discount,
    Discount_UnitType,
    Description,
    NULL AS Related_Order_Code,
    NULL AS Related_item_Code,
    Employee_id,
    split_pct,
    CloseDate,
    Monthly_Validation,
    Churn_Date,
    Final_ARR_Growth,
    Final_ARR_Growth_UnitType,
    StageName,
    Related_Contract_ARR,
    Related_Contract_ARR_UnitType,
    Final_Contract_ARR,
    Final_Contract_ARR_UnitType,
    Reseller_Account,
    --Reseller_Account_UnitType,
    Approval_Done,
    Renewal_ARR,
    Renewal_ARR_UnitType,
    Deal_Date,
    Renewal_Type,
    Record_Type_Name,
    Out_of_Recovery_Period,
    Lead_Source,
    Opportunity_Description,
    Previous_ARR,
    Previous_ARR_UnitType,
    Consulting,
    Consulting_UnitType,
    Product_Type,
    Approval_Manager,
    ARR_Number_of_months,
    ARR_Number_of_months_UnitType,
    --Downsell,
    --Downsell_UnitType,
    --Churn,
    --Churn_UnitType,
    --Opening,
    --Opening_UnitType,
    Order_Process_Date,
    End_User_Country,
    Shipped_to_country,
    Approval_Process_Created_Date,
    Approval_Process_Role,
    System_Approval_Description,
    NULL as split_amount_pct,
    Co_Termed_Unused_ARR,
    Co_Termed_Unused_ARR_UnitType,
    Opp_Solution_Engineer,
    Opp_Cloud_Migration,
    Opp_Final_Number_of_Month,
    Opp_Opp_Platform,
    Opp_Strategic_Opp_Solution_Architect_name,
    Opp_Strategic_Opp_Solution_Architect,
    Business_Unit_Territory,
    Business_Unit_Pod,
    Business_Unit_Tier_Level,
    Business_Unit_Tier_Manager_Name,
    Business_Unit_Tier_Manager_ID,
    Business_Unit_Regional_VP_Name,
    Business_Unit_Pod_Manager_Name,
    Opp_CSM,
    Opp_Type,
    Opp_Owner_Name,
    Opp_Comp_Credit,
    PS_Net_Amount,
    JAS_Net_Amount,
    Co_Sell_Program_Opportunity,
    Marketplace_Offer_ID,
    Partner_Lead_Source,
    PRM_Opportunity_Origination,
    Cloud_Alliance_Partner,
    Qualified_Prospect,
    Security_Final_ARR_Growth,
    Security_Final_ARR_Growth_UnitTypeName,
    Security_Net_Amount,
    Security_Net_Amount_UnitTypeName,
    Cloud_Alliance_Co_Sell_Opportunity__c,
    Cloud_Alliance_Opportunity_ID__c
    , Meeting_Status
    , Final_Qualified_Product
    , Purchase_Type
    , Is_Monthly_Subscription_Product
    from delta.pstg_order_item_churn_prestage a
    join delta.pstg_order_item_churn_order_count b on a.order_code = b.new_order_code
    where ToInteger(b.order_cnt) > 1
    and a.System_Approval_Description = 'Expiring ARR'
    union
    SELECT
    Order_Code,
    item_code,
    Batch_Name,
    Batch_Type,
    period_name,
    Product_name,
    Geography_name,
    Customer_Name,
    Quantity,
    Amount,
    amount_UnitType,
    incentive_date,
    Order_Date,
    order_type,
    Discount,
    Discount_UnitType,
    Description,
    NULL AS Related_Order_Code,
    NULL AS Related_item_Code,
    Employee_id,
    split_pct,
    CloseDate,
    Monthly_Validation,
    Churn_Date,
    Final_ARR_Growth,
    Final_ARR_Growth_UnitType,
    StageName,
    Related_Contract_ARR,
    Related_Contract_ARR_UnitType,
    Final_Contract_ARR,
    Final_Contract_ARR_UnitType,
    Reseller_Account,
    --Reseller_Account_UnitType,
    Approval_Done,
    Renewal_ARR,
    Renewal_ARR_UnitType,
    Deal_Date,
    Renewal_Type,
    Record_Type_Name,
    Out_of_Recovery_Period,
    Lead_Source,
    Opportunity_Description,
    Previous_ARR,
    Previous_ARR_UnitType,
    Consulting,
    Consulting_UnitType,
    Product_Type,
    Approval_Manager,
    ARR_Number_of_months,
    ARR_Number_of_months_UnitType,
    --Downsell,
    --Downsell_UnitType,
    --Churn,
    --Churn_UnitType,
    --Opening,
    --Opening_UnitType,
    Order_Process_Date,
    End_User_Country,
    Shipped_to_country,
    Approval_Process_Created_Date,
    Approval_Process_Role,
    System_Approval_Description,
    NULL as split_amount_pct,
    Co_Termed_Unused_ARR,
    Co_Termed_Unused_ARR_UnitType,
    Opp_Solution_Engineer,
    Opp_Cloud_Migration,
    Opp_Final_Number_of_Month,
    Opp_Opp_Platform,
    Opp_Strategic_Opp_Solution_Architect_name,
    Opp_Strategic_Opp_Solution_Architect,
    Business_Unit_Territory,
    Business_Unit_Pod,
    Business_Unit_Tier_Level,
    Business_Unit_Tier_Manager_Name,
    Business_Unit_Tier_Manager_ID,
    Business_Unit_Regional_VP_Name,
    Business_Unit_Pod_Manager_Name,
    Opp_CSM,
    Opp_Type,
    Opp_Owner_Name,
    Opp_Comp_Credit,
    PS_Net_Amount,
    JAS_Net_Amount,
    Co_Sell_Program_Opportunity,
    Marketplace_Offer_ID,
    Partner_Lead_Source,
    PRM_Opportunity_Origination,
    Cloud_Alliance_Partner,
    Qualified_Prospect,
    Security_Final_ARR_Growth,
    Security_Final_ARR_Growth_UnitTypeName,
    Security_Net_Amount,
    Security_Net_Amount_UnitTypeName,
    Cloud_Alliance_Co_Sell_Opportunity__c,
    Cloud_Alliance_Opportunity_ID__c
    , Meeting_Status
    , Final_Qualified_Product
    , Purchase_Type
    , Is_Monthly_Subscription_Product
    from delta.pstg_order_item_churn_prestage a
    join delta.pstg_order_item_churn_order_count b on a.order_code = b.new_order_code
    where b.order_cnt = '1';
)