p_holdout_splits_load_preprocess

s_d2c_load_orders_pre_process
    set PERIOD_NAME *= :PERIOD_NAME;
    set PG_NAME *= :PG_NAME;
    set PARAM_EXT_TASK_ID *=:PARAM_EXT_TASK_ID;
    set EXT_OBJECT_NAME *=:EXT_OBJECT_NAME;
    set CUST_BUSINESS_ID *=:CUST_BUSINESS_ID;
    set v_period_name *= :PERIOD_NAME;
    set v_process_name *= :PG_NAME;
    set v_pipeline_name *=:EXT_OBJECT_NAME;
    set v_ext_task_id *=:PARAM_EXT_TASK_ID;
    set v_customer_name *=:CUST_BUSINESS_NAME;
    set v_podname *= PodName();
    set v_shared_customer_name *= :v_customer_name || '-' ||SubString(:v_podname,11);
    set v_email_from *='delta-notifications@xactlycorp.com';
    set v_business_id *=:CUST_BUSINESS_ID;
    set Email_Distribution_List *= :Email_Distribution_List;
    set v_email_to *= :Email_Distribution_List||',delta-notifications@xactlycorp.com';
    set v_email_to_error *= :v_email_to;
    set v_param_processing_period *= :PERIOD_NAME;
    set v_param_shared_customer_name *= :JFrog;
    set v_param_email_distribution_list *= :Email_Distribution_List;

p_set_v_process_variables
    s_register_incent_user
    incent credential (Username=:v_param_incent_user_name, Password=:v_param_incent_pw)
    s_set_v_sfdc_user_name
    SET v_sfdc_user *= v_param_sfdc_user_name
    s_set_v_sfdc_pw
    SET v_sfdc_passwd *= v_param_sfdc_pw
    s_set_v_shared_customer_name
    SET v_shared_customer_name *= v_param_shared_customer_name
    s_set_v_daily_process_incent_period
    SET v_daily_process_incent_period *=SELECT Name FROM xactly.xc_period per JOIN (SELECT MIN(START_DATE) SD FROM xactly.xc_period per JOIN xactly.xc_period_type pertyp ON per.PERIOD_TYPE_ID_FK=pertyp.PERIOD_TYPE_ID WHERE per.IS_OPEN = 1 AND pertyp.Name='MONTHLY') MinStart ON MinStart.SD = per.START_DATE JOIN xactly.xc_period_type pertyp ON per.PERIOD_TYPE_ID_FK=pertyp.PERIOD_TYPE_ID AND pertyp.Name='MONTHLY'
    s_set_v_var_sales_data_pp_unfinalized
    SET v_var_sales_data_pp_unfinalized *= (
    SELECT
    CASE
    WHEN count(*) = 0 THEN TRUE
    ELSE FALSE
    End as unfin
    FROM (
    SELECT
    per.name
    , count(*) as ct
    FROM xactly.xc_period per
    JOIN xactly.xc_finalize_business_group fin
    ON (per.PERIOD_ID = fin.PERIOD_ID)
    JOIN xactly.xc_finalize_payment fp
    ON (fp.finalize_id = fin.finalize_id
    AND fp.finalize_type <> 'Preview')
    WHERE per.name = :v_param_processing_period
    ) bg
    )
    s_set_v_var_sales_data_pp_start_date
    SET v_var_sales_data_pp_start_date *= (
    SELECT
    per.start_date
    FROM xactly.xc_period per
    WHERE per.name = :v_param_processing_period)
    s_set_v_var_sales_data_pp_end_date
    SET v_var_sales_data_pp_end_date *= (
    SELECT
    per.end_date
    FROM xactly.xc_period per
    WHERE per.name = :v_param_processing_period)
    s_set_v_var_sales_data_pp_start_date
    SET v_var_sales_data_pp_start_date *= (
    SELECT
    per.start_date
    FROM xactly.xc_period per
    WHERE per.name = :v_param_processing_period)
    s_set_v_var_sales_data_pp_end_date
    SET v_var_sales_data_pp_end_date *= (
    SELECT
    per.end_date
    FROM xactly.xc_period per
    WHERE per.name = :v_param_processing_period)
    s_set_env_var
    set v_sfdc_env *= v_param_sfdc_env


Create step s_set_start_email_subject_holdout_splits_load_process AS (
set v_email_subject *=:v_shared_customer_name ||' - Process '||:v_process_name||' started for period '||:v_period_name;
set v_generic_email_body = 'Auto generated by Xactly Connect <br> For documentation: https://helpcenter.xactlycorp.com/ <br>For help, reach out to Xactly Support via the Customer Support Portal in Incent';
)

s_send_generic_email
Send email e_genereic_email
