i_incentive_details_export_manager

p_incentive_details_export_manager_write_process
SELECT DISTINCT CE.Report_Separator as v_Report_Separator FROM delta.Incentive_Details_export_manager_rpt CE WHERE CE.Report_Separator IS NOT NULL
