p_incentive_details_export_distribute_process

Create step s_incentive_details_report_file_path as (
SET v_report_file_path *= Concat('/Outbound/Incentive_Details_',Today(),'/Incentive_Details_',:v_Report_Separator,'_',Today(),'.csv');
)

Create step s_set_incentive_details_distribute_email AS (
Set v_email_subject *= :v_shared_customer_name||'- Incentive Details Report for '||:v_period_name;
Set v_email_body *= :v_shared_customer_name||'- Incentive Details Report for '||:v_period_name||'<br> Auto generated by Xactly Connect. <br> For more information contact: href="mailto:charusheelap@jfrog.com">Charusheela Pawar <br> ';
)

Create step s_incentive_details_write_report as (
call WriteFile(FilePath=:v_report_file_path,
    Input=(SELECT C1, C2, C3, C4, C5, C6, C7, C8, C9, C10, C11, C12, C13, C14, C15, C16
    FROM delta.Incentive_Details_Export_rpt WHERE Report_Separator =:v_Report_Separator order by Row ASC),
FirstLineNames=false,
Separator=',',
Quote='"',
Append=false,
Trim=true);
)

Create step s_set_email_to_distribute AS ( Set v_email_to *= :v_distribute_email)


Create Email e_genereic_email_att_distribute AS( 
"To" = :v_email_to 
, "From"=:v_email_from
, "Subject"=:v_email_subject 
, "BodyType" = 'HTML'
, "Body"=:v_email_body
, "Attachment1" = :v_report_file_path
)


Create step s_send_generic_email_att_distribute AS (Send email e_genereic_email_att_distribute);