Incentive Details Export Postprocess
p_incentive_details_export_post_process

Create step s_set_incentive_details_zip_destination AS (
Set v_set_incentive_details_zip_destination *= '/Outbound/Incentive_Details/Incentive_Details_'||Today()||'.zip'
)

Create step s_zip_incentive_details_reports AS (
call ZipFile(Directory='/Outbound/Incentive_Details_'||Today()
    ,Destination='/Outbound/Incentive_Details/Incentive_Details_'||Today()||'.zip'
    ,Recursive = true
    ,Overwrite = true)
)

DeleteFile(Directory='/Outbound/Incentive_Details_'||Today(), Recursive=true)

Create step s_set_incentive_details_complete_email AS (
Set v_email_subject *= :v_shared_customer_name||'-'|| v_process_name||' has completed for '||:v_Reporting_Period_Names;
Set v_email_body *= :v_shared_customer_name||'-'|| v_process_name||' has completed for '||:v_Reporting_Period_Names||'<br> Auto generated by Xactly Connect <br> ';
)

Create Email IF Exists e_genereic_email_att AS( 
"To" = :v_email_to 
, "From"=:v_email_from
, "Subject"=:v_email_subject 
, "BodyType" = 'HTML'
, "Body"=:v_email_body
, "Attachment1" = :v_set_incentive_details_zip_destination
)

Create step s_send_generic_email_att AS (Send email e_genereic_email_att);